src/app/routes/auth.py
from flask import Blueprint, redirect, url_for, render_template, request, flash
from flask_login import current_user, login_user, logout_user
from app.models import User
from app import db
from sqlalchemy.exc import IntegrityError

auth_bp = Blueprint("auth", __name__)


# ユーザー登録ページ
@auth_bp.route("/register", methods=["GET"])
def register_get():
    if current_user.is_authenticated:
        return redirect(url_for("main.index_get"))

    return render_template("auth/register.html")


# ユーザー登録 API
@auth_bp.route("/register", methods=["POST"])
def register_post():
    user_name = request.form.get("user_name")
    mail = request.form.get("mail")
    password = request.form.get("password")

    if not user_name or not mail or not password:
        flash("全てのフィールドを入力してください")
        return redirect(url_for("auth.register_get"))

    try:
        user = User(name=user_name, mail=mail)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

    except IntegrityError:
        db.session.rollback()
        flash("このメールアドレスは既に登録されています。")
        return redirect(url_for("auth.register_get"))

    return redirect(url_for("auth.login_get"))


# ログインページ
@auth_bp.route("/login", methods=["GET"])
def login_get():
    if current_user.is_authenticated:
        return redirect(url_for("main.index_get"))

    return render_template("auth/login.html")


# ログイン API
@auth_bp.route("/login", methods=["POST"])
def login_post():
    mail = request.form.get("mail")
    password = request.form.get("password")

    if not mail or not password:
        flash("メールアドレスとパスワードを入力してください")
        return redirect(url_for("auth.login_get"))

    user = User.query.filter_by(mail=mail).one_or_none()
    if user is None or not user.check_password(password):
        flash("メールアドレスかパスワードが間違っています")
        return redirect(url_for("auth.login_get"))

    login_user(user)
    return redirect(url_for("main.index_get"))


# ログアウト API
@auth_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index_get"))

src/app/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user
from app import db
from sqlalchemy import func
from app.models import (
    User,
    QuestionList,
    Question,
    Option,
    AnswerResult,
    ImportList,
    BookmarkList,
)

main_bp = Blueprint("main", __name__)


# Top ページ
@main_bp.route("/", methods=["GET"])
def index_get():
    if current_user.is_authenticated:
        created_lists = QuestionList.query.filter_by(creator_id=current_user.id).all()
        created_list_ids = [created_list.id for created_list in created_lists]
        created_list_titles = [
            question_list.list_title for question_list in created_lists
        ]

        imported_lists = ImportList.query.filter_by(user_id=current_user.id).all()
        imported_list_ids = [imported_list.list_id for imported_list in imported_lists]
        imported_list_titles = [
            QuestionList.query.get(imported_list.list_id).list_title
            for imported_list in imported_lists
        ]

        bookmarked_lists = BookmarkList.query.filter_by(user_id=current_user.id).all()
        bookmarked_list_ids = [
            bookmarked_list.list_id for bookmarked_list in bookmarked_lists
        ]
        bookmarked_list_titles = [
            QuestionList.query.get(bookmarked_list.list_id).list_title
            for bookmarked_list in bookmarked_lists
        ]

    else:
        created_list_ids = []
        created_list_titles = []
        imported_list_ids = []
        imported_list_titles = []
        bookmarked_list_ids = []
        bookmarked_list_titles = []

    return render_template(
        "index.html",
        created_list_ids=created_list_ids,
        created_list_titles=created_list_titles,
        imported_list_ids=imported_list_ids,
        imported_list_titles=imported_list_titles,
        bookmarked_list_ids=bookmarked_list_ids,
        bookmarked_list_titles=bookmarked_list_titles,
    )


# 問題リスト機能
## リスト作成ページ
@main_bp.route("/question", methods=["GET"])
def create_question_get():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))

    return render_template("question/question.html")


## リスト作成 API
@main_bp.route("/question", methods=["POST"])
def create_question_post():
    form_data = request.form.to_dict()
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))

    # フォームのデータを変換
    json_data = {"list_title": form_data["list_title"], "question": {}}
    for key in form_data.keys():
        if key.startswith("question"):
            question_num = key.split("question")[1]
            question = {
                "question_text": form_data[key],
                "option": [],
                "answer": form_data["answer" + question_num],
            }
            for i in range(1, 5):
                option_key = "option" + question_num + "-" + str(i)
                if option_key in form_data:
                    question["option"].append(form_data[option_key])
            json_data["question"][question_num] = question

    # 問題リストの内容をデータベースに格納
    creator_id = current_user.id
    list_title = json_data["list_title"]
    question_list = QuestionList(creator_id=creator_id, list_title=list_title)
    db.session.add(question_list)
    db.session.commit()

    # 問題の内容をデータベースに格納
    list_id = question_list.id
    questions_data = json_data["question"]
    for key, question_data in questions_data.items():
        question_text = question_data["question_text"]
        correct_answer = question_data["answer"]
        question = Question(
            list_id=list_id, question_text=question_text, correct_answer=correct_answer
        )
        db.session.add(question)
        db.session.commit()

        # 問題の選択肢をデータベースに格納
        question_id = question.id
        options_data = question_data["option"]
        for option_text in options_data:
            option = Option(question_id=question_id, option_text=option_text)
            db.session.add(option)
        db.session.commit()

    return redirect(url_for("main.index_get"))


## リスト削除 API
@main_bp.route("/question/delete/<list_id>", methods=["GET"])
def delete_question(list_id):
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))
    question_list = QuestionList.query.filter_by(
        id=list_id, creator_id=current_user.id
    ).first()
    if question_list:
        try:
            BookmarkList.query.filter_by(list_id=question_list.id).delete()
            ImportList.query.filter_by(list_id=question_list.id).delete()
            AnswerResult.query.filter_by(list_id=question_list.id).delete()
            questions = question_list.questions
            for question in questions:
                Option.query.filter_by(question_id=question.id).delete()
            Question.query.filter_by(list_id=question_list.id).delete()
            db.session.delete(question_list)
            db.session.commit()
        except Exception:
            return redirect(url_for("main.index_get"))
    return redirect(url_for("main.index_get"))


# リスト回答機能
## 問題リストの回答ページ
@main_bp.route("/question/<list_id>", methods=["GET"])
def question_content_get(list_id):
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))
    question_list = QuestionList.query.get(list_id)
    if not question_list:
        return render_template("not_found.html")

    # 問題リストの内容を取得
    list_title = question_list.list_title
    creator = User.query.get(question_list.creator_id)
    creator_name = creator.name
    questions = [question.question_text for question in question_list.questions]
    options = []
    for question in question_list.questions:
        question_options = [option.option_text for option in question.options]
        options.append(question_options)

    return render_template(
        "question/question_content.html",
        list_title=list_title,
        creator_name=creator_name,
        questions=questions,
        options=options,
    )


## 問題リストの回答 API
@main_bp.route("/question/<list_id>", methods=["POST"])
def question_content_post(list_id):
    form_data = request.form.to_dict()
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))
    question_list = QuestionList.query.get(list_id)
    if not question_list:
        return render_template("not_found.html")
    correct_answers = [question.correct_answer for question in question_list.questions]

    # ユーザの回答をデータベースに格納
    max_result_list_id = db.session.query(
        func.max(AnswerResult.result_list_id)
    ).scalar()
    if max_result_list_id == None:
        result_list_id = 0
    else:
        result_list_id = max_result_list_id + 1
    results = []
    for key, value in form_data.items():
        question_key = int(key[8:])
        answerer_id = current_user.id
        question_id = question_list.questions[question_key - 1].id
        user_answer = int(value)
        answer_result = AnswerResult(
            result_list_id=result_list_id,
            answerer_id=answerer_id,
            list_id=list_id,
            question_id=question_id,
            user_answer=user_answer,
        )
        db.session.add(answer_result)
        db.session.commit()
        results.append(user_answer)

    # 問題リストの内容を取得
    list_title = question_list.list_title
    try:
        answerer_name = User.query.get(answerer_id).name
    except:
        return render_template("not_found.html")
    questions = [question.question_text for question in question_list.questions]
    options = []
    for question in question_list.questions:
        question_options = [option.option_text for option in question.options]
        options.append(question_options)

    return render_template(
        "question/question_result.html",
        list_id=list_id,
        list_title=list_title,
        questions=questions,
        options=options,
        results=results,
        correct_answers=correct_answers,
        answerer_name=answerer_name,
    )


# 回答結果機能
## 回答結果の一覧ページ
@main_bp.route("/question/result/<list_id>", methods=["GET"])
def question_result(list_id):
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login_get"))
    question_list = QuestionList.query.get(list_id)
    if not question_list:
        return render_template("not_found.html")

    # リスト作成者のみ閲覧可能
    creator = User.query.get(question_list.creator_id)
    creator_id = creator.id
    if creator_id != current_user.id:
        return render_template("not_found.html")

    # 問題リストの内容を取得
    list_title = question_list.list_title

    # 問題リストの回答状況を取得
    answer_results = AnswerResult.query.filter_by(list_id=list_id).all()
    result_list_ids = [result.result_list_id for result in answer_results]
    if not result_list_ids:
        return render_template("not_found.html")
    result_list_ids_unique = list(set(result_list_ids))
    count = int(
        (len(result_list_ids) - len(result_list_ids_unique))
        / len(result_list_ids_unique)
    )
    answerer_ids = [result.answerer_id for result in answer_results]
    answerer_names = []
    for i, answerer_id in enumerate(answerer_ids):
        if i % (count + 1) != 0:
            continue
        user = User.query.get(answerer_id)
        answerer_names.append(user.name)

    return render_template(
        "question/question_result_list.html",
        list_id=list_id,
        list_title=list_title,
        result_list_ids=result_list_ids_unique,
        answerer_names=answerer_names,
    )


## 回答結果の詳細ページ
@main_bp.route("/question/result/<list_id>/<result_list_id>", methods=["GET"])

src/app/templates/index.html
<!DOCTYPE html>
<html lang="jp">

<head>
    <meta charset="UTF-8">
    <title>Top / SOPHIST</title>
    <link rel="icon" href="../static/favicon.png">
</head>

<body>
    {% extends "layout.html" %}
    {% block content %}
    {% if current_user.is_authenticated %}
    <div class="ml-10 my-2 text-2xl text-yellow-600">
        ようこそ {{ current_user.name }} 様
    </div>

    <!--アコーディオン-->
    <div class="ml-14 mb-10">
        <div x-data="{ isOpen: true }" class="w-fit mt-5">
            <div @click="isOpen = !isOpen" class="w-fit text-xl cursor-pointer">
                <span x-show="!isOpen">▶</span>
                <span x-show="isOpen">▼</span>
                Bookmark List
            </div>
            <ul x-show="isOpen" class="mt-2">
                <!--リストカード-->
                <li class="flex flex-wrap">
                    {% for index in range(bookmarked_list_titles|length) %}
                    {% set list_title = bookmarked_list_titles[index] %}
                    {% set list_id = bookmarked_list_ids[index] %}
                    <div
                        class="m-2 w-[200px] h-[125px] border rounded-md border-yellow-600 bg-gray-50 overflow-hidden hover:shadow-xl flex flex-col items-center">
                        <div class="w-[200px] pl-2 bg-white flex justify-between items-center border-b-2 border-stone-300 rounded-md"
                            x-data="{open_etc: false}">
                            <div class="text-xl">List ID: {{ list_id }}</div>
                            <div>
                                <span class="cursor-pointer font-bold text-xl" @click="open_etc = true">︙</span>

                                <!--リスト詳細メニュー-->
                                <span x-show="open_etc" @click.away="open_etc = false">
                                    <div
                                        class="absolute flex flex-col p-2 bg-white rounded rop-shadow-2xl divide-y border border-gray-200">
                                        <a href="{{ url_for('main.delete_bookmark', list_id=list_id)}}"
                                            class="py-2">ブックマークから削除</a>
                                    </div>
                                </span>
                            </div>
                        </div>
                        <a href="{{ url_for('main.question_content_get', list_id=list_id)}}"
                            class="w-[180px] h-[76px] bg-white mt-2 px-1 rounded-sm cursor-pointer border border-gray-200 overflow-hidden">
                            <div class="overflow-hidden">{{ list_title }}</div>
                        </a>
                    </div>
                    {% endfor %}
                </li>
            </ul>
        </div>

        <div x-data="{ isOpen: true }" class="w-fit h-fit mt-5">
            <div @click="isOpen = !isOpen" class="w-fit text-xl cursor-pointer">
                <span x-show="!isOpen">▶</span>
                <span x-show="isOpen">▼</span>
                Created List
            </div>
            <ul x-show="isOpen" class="mt-2">
                <!--リストカード-->
                <li class="flex flex-wrap">
                    {% for index in range(created_list_titles|length) %}
                    {% set list_title = created_list_titles[index] %}
                    {% set list_id = created_list_ids[index] %}
                    <div
                        class="m-2 w-[200px] h-[125px] border rounded-md border-yellow-600 bg-gray-50 overflow-hidden hover:shadow-xl flex flex-col items-center">
                        <div class="w-[200px] pl-2 bg-white flex justify-between items-center border-b-2 border-stone-300 rounded-md"
                            x-data="{open_etc: false}">
                            <div class="text-xl">List ID: {{ list_id }}</div>
                            <div>
                                <span class="cursor-pointer font-bold text-xl" @click="open_etc = true">︙</span>

                                <!--リスト詳細メニュー-->
                                <span x-show="open_etc" @click.away="open_etc = false">
                                    <div
                                        class="absolute flex flex-col p-2 bg-white rounded rop-shadow-2xl border border-gray-200">
                                        <a href="{{ url_for('main.question_result', list_id=list_id)}}"
                                            class="py-2">回答データ</a>
                                        <a href="{{ url_for('main.bookmark_question', list_id=list_id)}}"
                                            class="py-2 border-y border-gray-300">ブックマークに追加</a>
                                        <a href="{{ url_for('main.delete_question', list_id=list_id)}}"
                                            class="py-2">問題リストを削除</a>
                                    </div>
                                </span>
                            </div>
                        </div>
                        <a href="{{ url_for('main.question_content_get', list_id=list_id)}}"
                            class="w-[180px] h-[76px] bg-white mt-2 px-1 rounded-sm cursor-pointer border border-gray-200 overflow-hidden">
                            <div class="overflow-hidden">{{ list_title }}</div>
                        </a>
                    </div>
                    {% endfor %}
                </li>
            </ul>
        </div>

        <div x-data="{ isOpen: true }" class="w-fit mt-5">
            <div @click="isOpen = !isOpen" class="w-fit text-xl cursor-pointer">
                <span x-show="!isOpen">▶</span>
                <span x-show="isOpen">▼</span>
                Imported List
            </div>
            <ul x-show="isOpen" class="mt-2">
                <!--リストカード-->
                <li class="flex flex-wrap">
                    {% for index in range(imported_list_titles|length) %}
                    {% set list_title = imported_list_titles[index] %}
                    {% set list_id = imported_list_ids[index] %}
                    <div
                        class="m-2 w-[200px] h-[125px] border rounded-md border-yellow-600 bg-gray-50 overflow-hidden hover:shadow-xl flex flex-col items-center">
                        <div class="w-[200px] pl-2 bg-white flex justify-between items-center border-b-2 border-stone-300 rounded-md"
                            x-data="{open_etc: false}">
                            <div class="text-xl">List ID: {{ list_id }}</div>
                            <div>
                                <span class="cursor-pointer font-bold text-xl" @click="open_etc = true">︙</span>

                                <!--リスト詳細メニュー-->
                                <span x-show="open_etc" @click.away="open_etc = false">
                                    <div
                                        class="absolute flex flex-col p-2 bg-white rounded rop-shadow-2xl divide-y border border-gray-200">
                                        <a href="{{ url_for('main.bookmark_question', list_id=list_id)}}"
                                            class="py-2">ブックマークに追加</a>
                                        <a href="{{ url_for('main.delete_import', list_id=list_id)}}"
                                            class="py-2 border-t border-gray-300">インポートから削除</a>
                                    </div>
                                </span>
                            </div>
                        </div>
                        <a href="{{ url_for('main.question_content_get', list_id=list_id)}}"
                            class="w-[180px] h-[76px] bg-white mt-2 px-1 rounded-sm cursor-pointer border border-gray-200 overflow-hidden">
                            <div class="overflow-hidden">{{ list_title }}</div>
                        </a>
                    </div>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    {% else %}
    <div class="ml-10 my-2 text-2xl text-yellow-600">
        ようこそ ゲスト 様
    </div>
    <div class="w-[1100px] h-[650px] mx-auto my-5 relative border-2 border-yellow-600 rounded-md">
        <div class="w-full h-full text-white text-5xl font-bold font-serif flex flex-col items-center justify-center">
            <div class="my-5">知識は美の源泉である。</div>
            <div class="my-5">知識を持つ者は、万物の不可思議なる絆を悟り</div>
            <div class="my-5">崇めることができる。</div>
            <div class="w-full mt-20 pr-5 text-right">Sophist. Zeno</div>
        </div>
        <img src="{{ url_for('static', filename='top.jpg') }}" class="absolute top-0 -z-10 w-full h-full" />
    </div>
    {% endif %}
    {% endblock %}
</body>

</html>

src/app/templates/layout.html
<!DOCTYPE html>
<html lang="jp">

<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>

<body class="tracking-widest overflow-x-hidden" x-data="{ open : false }">
    <header class="flex flex-col">
        <div class="w-screen h-28 bg-black flex justify-center">
            <div class="w-[1200px] min-w-[400px] relative">
                <div class="w-full h-full absolute flex flex-col items-center justify-center">
                    <img src="{{ url_for('static', filename='favicon.png') }}" class="w-16 h-16" />
                    <div
                        class="font-serif text-transparent text-3xl bg-clip-text bg-gradient-to-r from-white to-yellow-600">
                        SOPHIST
                    </div>
                </div>
                <div class="w-full h-full absolute flex flex-col items-end justify-center">
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('auth.logout') }}" 
                        class="w-16 flex flex-col items-center justify-center mr-4">
                        <img src="{{ url_for('static', filename='usericon.png') }}" class="w-9 h-9" />
                        <div class="text-yellow-300 text-xs text-center mt-2 tracking-wider">
                            ログアウト
                        </div>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.login_get') }}"
                        class="w-16 flex flex-col items-center justify-center mr-4">
                        <img src="../static/usericon.png" class="w-9 h-9" />
                        <div class="text-yellow-300 text-xs text-center mt-2">
                            ログイン
                        </div>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w-screen h-12 bg-yellow-950 flex justify-center">
            <div class="w-[1200px] min-w-[400px] relative">
                <div class="w-full h-full absolute flex items-center justify-end">
                    <a href="{{ url_for('main.create_question_get') }}"
                        class="mr-6 font-bold text-white tracking-widest hover:text-yellow-300">
                        Create
                    </a>
                    <button @click="open = true"
                        class="mr-6 font-bold text-white tracking-widest hover:text-yellow-300">
                        Import
                    </button>
                </div>
            </div>
        </div>
        <a href="{{ url_for('main.index_get') }}"
            class="absolute left-0 right-0 mt-[5px] mx-auto w-[65px] h-[65px]"></a>
        <a href="{{ url_for('main.index_get') }}"
            class="absolute left-0 right-0 mt-[70px] mx-auto w-[140px] h-[30px]"></a>
    </header>
    <main class="flex justify-center">
        <div class="w-[1200px] min-w-[400px]">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <div x-show="open" class="absolute top-0 left-0 w-screen h-screen">
        <div @click="open = false" class="flex justify-center items-center w-full h-full bg-black bg-opacity-80">
            <div @click.stop="open = true" class="w-[400px] h-[130px] bg-white border rounded-md">
                <div class="mt-2 ml-5 font-bold text-2xl">List ID</div>
                <form action="/question/import" method="POST" class="flex justify-center items-center mt-2">
                    <input name="import" class="w-[200px] h-[50px] pl-2 border-2 font-bold text-2xl tracking-widest rounded-sm" />
                    <button @click.stop="open = false" type="submit"
                        class="w-[100px] h-[50px] bg-yellow-950 text-white text-xl font-bold rounded-sm">
                        Import
                    </button>
                </form>
                <!-- <div class="flex justify-center items-center mt-1 text-red-500">正しい List ID を入力してください</div> -->
            </div>
        </div>
    </div>
</body>

</html>

src/app/templates/not_found.html
<!DOCTYPE html>
<html lang="jp">

<head>
    <meta charset="UTF-8">
    <title>404 Not Found</title>
</head>

<body>
    <h1 class="text-xl">Not Found</h1>
    The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
</body>

</html>